name: approvify

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: PREPARE
    steps:
    - name: Create File
      run: echo "sample text" >> sample.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sample
        path: './'
  download:
    runs-on: ubuntu-latest
    environment: PLAYGROUND
    needs: [upload]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: sample
        path: './sample'
    - name: Read File
      run: cat ./sample/sample.txt