name: approvify

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: step 1
      run: echo "sample text" >> ./sample/sample.txt
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sample
        path: './sample'
  download:
    runs-on: ubuntu-latest
    environment: test
    needs: [upload]
    steps:
    - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: sample
          path: './sample'
    - name: read file
        run: cat sample.txt